load("@rules_java//java:defs.bzl", "java_binary")

java_binary(
    name = "grpc-client",
    srcs = [
        "GRpcClient.java"
    ],
    main_class = "com.example.grpc.client.GRpcClient",
)

#java_import(
#    name = "local-lib",
#    jars = [
#        "@maven//:com_google_code_gson_gson"
#    ],
#    deps = [],
#)
#java_library(
#    name = "demo-lib",
#    srcs = glob(["src/main/java/com/example/*.java"]),
#    deps = [
#        "@maven//:com_google_code_gson_gson",
#    ],
#)

